# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "James T. Brown | Entomology | UCANR Kearney REC"
title_separator          : "-"
name                     : &name "James T. Brown, PhD"
description              : &description "Postdoctoral entomologist specializing in biological control, IPM, invasive pest ecology, and agroecosystem sustainability."
url                      : https://jtbentomology.github.io
baseurl                  : ""
repository               : "jtbentomology/jtbentomology.github.io"

# Favicon
favicon                  : "/images/farm_4661507.png"

# Site Author
author:
  # Biographic information
  avatar           : "/images/IMG_9450.png"
  name             : "James T. Brown, PhD"
  pronouns         :
  bio              : "Postdoctoral Research Scholar in entomology specializing in biological control, integrated pest management (IPM), and invasive insect ecology. Research focuses on vineyard and specialty crop systems, classical biological control of Drosophila suzukii, vine mealybug management, insecticide evaluation, and agroecosystem sustainability across conventional, organic, and natural systems."
  location         : "UCANR Kearney Research & Extension Center, Parlier, CA"
  employer         : "University of California, Berkeley â€“ UCANR Kearney Research & Extension Center"
  uri              :
  email            : "none@example.org" 

  # Academic websites
  academia         :
  arxiv            :
  googlescholar    : "https://scholar.google.com/citations?user=9TGkqF8AAAAJ&hl=en"
  inspire-hep      :
  impactstory      :
  orcid            : "https://orcid.org/0000-0003-3195-6761"
  semantic         :
  ssrn             :
  pubmed           :
  researchgate     :   # removed
  scopus           :
  zotero           :

  # Repositories and software development
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "jtbentomology"
  kaggle           :
  stackoverflow    :

  # Social media
  artstation       :
  bluesky          :
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "james-brown-565b8613"
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram         :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          :
  zhihu            :

navigation: # The following is the order of the links in the header of the website.
#
# Changing the order here will adjust the order and you can also add additional
# links. Removing a link prevents it from showing in the header, but does not
# prevent it from being included in the site.
#
# NOTE that only one of the CV options should be selected, the first is for the
#      Markdown formatted page while the second is generated using JSON.

main:
  - title: "Publications"
    url: /publications/

  - title: "Talks"
    url: /talks/    

  - title: "Teaching"
    url: /teaching/    
    
  - title: "Portfolio"
    url: /portfolio/
        
  - title: "Blog Posts"
    url: /year-archive/
    
  - title: "CV"
    url: /cv/
    
  # - title: "CV"
  #   url: /cv-json/
    
  - title: "Guide"
    url: /markdown/
