# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "James T. Brown | Entomology | UCANR Kearney REC"
title_separator          : "-"
name                     : &name "James T. Brown, PhD"
description              : &description "Postdoctoral entomologist specializing in biological control, IPM, invasive pest ecology, and agroecosystem sustainability."
url                      : https://academicpages.github.io
baseurl                  : ""
repository               : "academicpages/academicpages.github.io"

# Favicon
favicon                  : "/images/farm_4661507.png"

# Site Author
author:
  # Biographic information
  avatar           : "IMG_9450.png"
  name             : "James T. Brown, PhD"
  pronouns         :
  bio              : "Postdoctoral Research Scholar in entomology specializing in biological control, integrated pest management (IPM), and invasive insect ecology. Research focuses on vineyard and specialty crop systems, classical biological control of Drosophila suzukii, vine mealybug management, insecticide evaluation, and agroecosystem sustainability across conventional, organic, and natural systems."
  location         : "UCANR Kearney Research & Extension Center, Parlier, CA"
  employer         : "University of California, Berkeley â€“ UCANR Kearney Research & Extension Center"
  uri              :
  email            : "none@example.org" 

  # Academic websites
  academia         :
  arxiv            :
  googlescholar    : "https://scholar.google.com/citations?user=9TGkqF8AAAAJ&hl=en"
  inspire-hep      :
  impactstory      :
  orcid            : "https://orcid.org/0000-0003-3195-6761"
  semantic         :
  ssrn             :
  pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  researchgate     :
  scopus           :
  zotero           :

  # Repositories and software development
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "academicpages"
  kaggle           :
  stackoverflow    :

  # Social media
  artstation       :
  bluesky          : "bsky.app"
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "james-brown-565b8613"
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram         :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          :
  zhihu            :
